<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for filter items block
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\FilterRenderer
 */
?>
<?php
foreach ($filterItems as $_item):
$cus_attr_code[] = $_item->getFilter()->getAttributeModel()->getAttributeCode();
endforeach;
?>
<?php if(count($filterItems) >= 6 ) { ?>
<input type = "text" class = "auto_sug_filter" placeholder = "<?php echo $this->getName() ;?>" name = "auto_sug_filter_<?php echo $cus_attr_code[0] ?>" id = "auto_sug_filter_<?php echo $cus_attr_code[0] ?>" placeholder="Search..."/>
<?php } ?>
<ol class="items checkbox-filter-wrapper" id = "<?php echo $cus_attr_code[0] ?>_wrapper">
    <?php foreach ($filterItems as $filterItem): ?>
        <li class="item">
            <?php if ($filterItem->getCount() > 0): ?>
                <a href="<?= $block->escapeUrl($filterItem->getUrl()) ?>">
                    <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                    <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                        <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                            <?php if ($filterItem->getCount() == 1):?> <?= /* @escapeNotVerified */ __('item') ?><?php else:?> <?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                    <?php endif; ?>
                </a>
            <?php $attr_array[$filterItem->getValue()] = $filterItem->getLabel() ; ?>
            <?php else:?>
                <?= /* @escapeNotVerified */ $filterItem->getLabel() ?>
                <?php if ($this->helper('\Magento\Catalog\Helper\Data')->shouldDisplayProductCountOnLayer()): ?>
                    <span class="count"><?= /* @escapeNotVerified */ $filterItem->getCount() ?><span class="filter-count-label">
                        <?php if ($filterItem->getCount() == 1):?><?= /* @escapeNotVerified */ __('item') ?><?php else:?><?= /* @escapeNotVerified */ __('items') ?><?php endif;?></span></span>
                <?php endif; ?>
            <?php endif; ?>
        </li>
    <?php endforeach ?>
</ol>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();   
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
?>
<style>
.checkbox-filter-wrapper
{
    max-height: 120px;
    overflow-y: auto;
}
</style>
<script>
  jQuery(function() {
    var attrArray = <?php echo json_encode($attr_array) ; ?> ;
    
    var attr_code =  '<?php echo $cus_attr_code[0] ; ?>' ;
    
    var current_html = jQuery("#<?php echo $cus_attr_code[0] ?>_wrapper").html();
    
    jQuery( "#auto_sug_filter_<?php echo $cus_attr_code[0] ?>" ).keyup(function()
    {
        if(jQuery(this).val())
        {
            var request = jQuery.ajax({
              url: "<?php echo $storeManager->getStore()->getBaseUrl() ; ?>index.php/easyfilter",
              type: "POST", 
              data: { query: jQuery(this).val(), alldata: attrArray, attrcode: attr_code, currenthtml: current_html },
              dataType: "json",
              success: function(response) { jQuery("#<?php echo $cus_attr_code[0] ?>_wrapper").html(response);},
              error: function(xhr, ajaxOptions, thrownError) { jQuery("#<?php echo $cus_attr_code[0] ?>_wrapper").html(xhr.responseText);}
            });
        }
        else
        {
            jQuery("#<?php echo $cus_attr_code[0] ?>_wrapper").html(current_html);
        }
    });
  });
</script>